# Generated by Django 4.2.6 on 2025-01-03 16:17

from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_role'),
        ('doctor', '0002_alter_patientprofile_phone_no_assigndoctor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='health_conditon',
            new_name='apponitment_reason',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='assignment_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_id',
            field=models.ForeignKey(default='ba12ab7c-f6b1-4ee8-8f29-26ecc3714c20', on_delete=django.db.models.deletion.CASCADE, to='doctor.patientprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='user_id',
            field=models.ForeignKey(default='fa0928af-9ced-4181-8527-45aa5a1fa44b', on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='DOB',
            field=models.DateTimeField(default=now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='Health_info',
            field=models.CharField(default='demo', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='Sex',
            field=models.CharField(default='male', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='blood_pressure',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='body_temp',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='weight',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='email_id',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='AssignDoctor',
        ),
    ]
