# Generated by Django 4.2.6 on 2025-01-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_rename_health_conditon_appointment_apponitment_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='DOB',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
