# Generated by Django 4.2.6 on 2025-01-03 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_patientprofile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='DOB',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
