# Generated by Django 4.2.6 on 2025-03-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_appointment_diagnosis_appointment_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='room_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
