# Generated by Django 4.2.6 on 2025-03-19 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_role'),
        ('doctor', '0007_appointment_room_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='user_id',
            field=models.ForeignKey(default='fa0928af-9ced-4181-8527-45aa5a1fa44b', on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
            preserve_default=False,
        ),
    ]
